version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=noter_test
      - POSTGRES_USER=noter
      - POSTGRES_PASSWORD=noter
    command: ["postgres"]
    ports:
      - "5432:5432"
