micronaut:
  server:
    port: 5001
  application:
    name: noter

netty:
  default:
    allocator:
      max-order: 3

ngrok:
  host: https://a676-77-238-132-138.ngrok.io
  local: http://localhost:5001

telegram:
  token: 5048393640:AAGA0cYs7DKEm92a6v_QcTDUEFVkIX0p87Q
  api: https://api.telegram.org
